---
title: |
  Informe de Consultoría 
  
  (**únicamente para casos de semestres anteriores**)
  
  **Caso I:** Dietas de Insentimentalina  
  *Efecto de cuatro dietas alienogensis sobre la vida sentimental de las aves*  
  **Grupo #9**

author: |
  **Ruimberto Hellman**^[rimhell@unal.edu.co], Universidad Nacional de Colombia  
  **Helmuth Peterhaim**^[HelmutPet@unal.edu.co], Universidad Nacional de Colombia  
  **Wilheim Mendez**^[wilheiMend@unal.edu.co], Universidad Nacional de Colombia  
  **Wimberto Hartman**^[rimhell@unal.edu.co], Universidad Nacional de Colombia
  
institute: |
  Departamento de Estadística  
  Facultad de Ciencias  
  Universidad Nacional de Colombia  
  Bogotá, Colombia

abstract: |
  El presente informe contiene los resultados de la consultoría "Título del documento pdf que les compartí"

  El experimento consiste en la aplicación de cuatro dietas con diferentes proporciones de Insentimentalina
  que actúan sobre el sistema sensorial de aves de rapiña. Entre los principales resultados se encuentra
  un modelo desbalanceado con efectos aleatorios no dinámicos a tres réplicas atemporales...

  
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    latex_engine: xelatex
fontsize: 12pt
geometry: margin=2.5cm
# bibliography: BiblioConsultoria1.bib
---

# Problema de investigación {#PrInv}

Describir aquí el problema desde el punto de vista del consultante.  


---

# Objetivo general

Describir aquí de manera muy general el objetivo de la investigación sin entrar en detalles de cómo se desarrollará la investigación, como se describe en el objetivo general del problema de investigación presentado en [la sección anterior](#PrInv).

*Establecer la variabilidad espacial de la amenaza por potencial de licuación[^1] a nivel aproximado para las zonas aluviales, lacustres y de llanura de inundación de Bogotá.*

[^1]: La licuefacción de suelos es un fenómeno en el cual los terrenos pierden la firmeza y por lo tanto las edificaciones se desplazan, se caen o se hunden.

---

# Objetivos específicos

- *Proponer una metodología para la evaluación del potencial de licuación.*
- *Establecer las condiciones geológicas, geomorfológicas, hidrogeológicas, geotécnicas y sísmicas de la zona de estudio.*
- *Establecer el potencial de licuación de la zona de estudio.*
- *Proponer una metodología para la zonificación de amenaza por potencial de licuación.*

---

# Problema(s) estadístico(s) por resolver {#ejem}

- *Establecer un modelo multivariado a partir de una base de datos histórica de licuación a nivel mundial.*
- *Caracterización geotécnica de materiales del subsuelo del área de estudio, a partir de información secundaria.*
- *Tratamiento de datos de información secundaria en procura de obtener correlaciones entre datos del ensayo SPT y los datos derivados de la exploración indirecta (VS30).*
- *Aplicar modelo definido de evaluación de potencial de licuación y generar la espacialización del potencial de licuación para el área de estudio.*
- *Diseñar y presentar metodología de estudio y zonificación de licuación apropiada para las zonas aluvial, lacustre y llanura de inundación de Bogotá.*

---


# Metodología sugerida por el consultante
Aquí solo incluir lo que sugiere el consultante si lo hizo, de lo contrario dejar en blanco

# Motodolgia propuesta por el grupo
Inclir aquí la metodología que el grupo utilizaría para resolver el problema, o para mejorar la propuesta del consultante.

# Observaciones y sugerencias de mejora para el consultante

# Revisión bibliográfica
**Fuentes propuestas por los consultantes:**  
- @gareth2021introduction  
- @pena2013analisis  
- @schoenberg1935remarks  
- @corradino1990proximity

**Fuentes consultadas por el grupo:**  
- @bib2  
- @lapointe1994classification

---


# Bibliografía



